### ISSUE TITLE
Max value of the gauge doesn't change

### ISSUE THREAD

**Issue by RamithRD** [Pygmalion69/Gauge#1]
Thank you very much for the gauge view, it suits well for IoT related projects.

I'm facing an issue setting the max value of the gauge, I want it to be 100 but it always defaults as 1000 even if I change the maxValue attribute.

```
<de.nitri.gauge.Gauge
        android:id="@+id/flow_rate_gauge"
        android:layout_width="250dp"
        android:layout_height="250dp"
        android:layout_gravity="center"
        android:layout_marginTop="10dp"
        gauge:initialValue="30"
         gauge:maxValue="100"
         gauge:minValue="0"
         gauge:totalNicks="120"
         gauge:valuePerNick="1" />

```

What am I missing here?

**Comment by Pygmalion69** [comment]
@RamithRD Sorry, I can't reproduce the issue. Here's what it looks like on my device:

<img width="303" alt="screen shot 2017-07-01 at 10 58 39" src="https://user-images.githubusercontent.com/6958566/27760625-76080570-5e4c-11e7-81ad-2ba63f03a619.png">
