### ISSUE TITLE
Different size of lowerText and upperText in landscape layout

### ISSUE THREAD

**Issue by eos1d3** [Pygmalion69/Gauge#10]
When using portrait layout, I set `lowerTextSize` and `upperTextSize` to 50dp. Then I add an landscape layout with similar settings in XML. But I find both text are much bigger in landscape layout. I have to reduce from 50 to 30 in order to make them look similar size in portrait layout.

Using `com.github.Pygmalion69:Gauge:1.5`

**Comment by Pygmalion69** [comment]
Thank you for reporting this. Text scaling on orientation change has been fixed (when the sizes are explicitly set).
