### ISSUE TITLE
App getting crashed

### ISSUE THREAD

**Issue by vigneshtg** [Pygmalion69/Gauge#12]
Hello,
I'm using USB Serial console for sending serial data for every 500 ms. Now I tried to use gauge view to display the data that I'm sending every 500 ms.
But the app is unfortunately not responding after certain time  when I've gauge view added to my app.

May I know the reason please?

Thank you

**Comment by Pygmalion69** [comment]
Do you have any more info? Code? Steps to reproduce? Logcat?

**Comment by vigneshtg** [comment]
Hello,
I'm using this app 
https://github.com/sugnakys/UsbSerialConsole
where, I'm adding the gauge view. But still getting crashed.

**Comment by Pygmalion69** [comment]
Insufficient information to reproduce the reported problem.
