### ISSUE TITLE
undeclared Thread? 

### ISSUE THREAD

**Issue by thirstyone** [Pygmalion69/Gauge#3]
https://github.com/Pygmalion69/Gauge/blob/ec200158218bf2a892071f1404b62ccc42012d43/app/src/main/java/de/nitri/gaugedemo/MainActivity.java#L54

**Comment by Pygmalion69** [comment]
The static method applies to the current thread.
https://stackoverflow.com/questions/17312048/java-why-thread-sleep-and-yield-are-static/17312097
