### ISSUE TITLE
TextSize on different devices

### ISSUE THREAD

**Issue by merc07** [Pygmalion69/Gauge#9]
I am using a Galaxy S6, 5inch and a Tab3, 7inch.
Even when the gauge is enlarged, to fit the same area using percentage, the text size on the Tab3 is massive compared with the S6.
This is true for the upper/lower text and the label text size.

In other words, a label text size of 48 on the S6 is perfect but on the Tab3, it will fill the whole gauge.

Is there a way around this so I can use the same software on multiple devices ?
Pics below, Tab3, S6

![screenshot_2018-08-09-22-46-28](https://user-images.githubusercontent.com/33531315/43927877-e11aead0-9c26-11e8-9227-cd228da44411.png)

![screenshot_20180807-000357 1](https://user-images.githubusercontent.com/33531315/43927897-efab77f4-9c26-11e8-9528-a3e31da68186.png)

**Comment by Pygmalion69** [comment]
Text sizes are now (107e249) in pixels at a screen width (= max. canvas width/height) of 1080 px and are scaled accordingly at different resolutions. E.g. a value of 48 is unchanged at 1080 x 1920 and scaled down to 27 at 600 x 1024.

**Comment by merc07** [comment]
Great work, thanks..
How do I implement this as I get the error 'AAPT2 error: check logs for details' when using 'com.github.Pygmalion69:Gauge:1.4.1' instead of 'com.github.Pygmalion69:Gauge:1.4'

**Comment by Pygmalion69** [comment]
Not sure. Try setting the target SDK to 28 and upgrading the Gradle plugin. As a last resort you can add `android.enableAapt2=false` to `gradle.properties`.

Note that this change will be in the next release, which is *1.5*.

**Comment by merc07** [comment]
SDK to 28 did the trick, also updated the plugin.
Text sizes are still as before though when run on the above devices

**Comment by Pygmalion69** [comment]
With release *1.5*?

**Comment by merc07** [comment]
Sorry, I may have missed that, v1.5 of what ?

**Comment by Pygmalion69** [comment]
Like this:

```
dependencies {
    implementation 'com.github.Pygmalion69:Gauge:1.5'
}
```

**Comment by merc07** [comment]
Ahh, I was using 1.41, thought that was the latest...works good with 1.5
Thanks !

**Comment by Pygmalion69** [comment]
You're welcome. Thank you for addressing this.

**Comment by Kelianbcn** [comment]
Hola, muchas gracias por tu trabajo , mi pregunta es ¿Está actualizado a Api 31 y en mavencentral?
